Repository madara-alliance/madara, pull requests merged in 2024-11, with the labels that each got.

#374 feat: get_compiled_casm (RPC)
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/client/block_import/Cargo.toml
  crates/client/db/Cargo.toml
  crates/client/db/src/block_db.rs
  crates/client/db/src/class_db.rs
  crates/client/db/src/db_metrics.rs
  crates/client/devnet/Cargo.toml
  crates/client/devnet/src/lib.rs
  crates/client/gateway/Cargo.toml
  crates/client/gateway/src/client/builder.rs
  crates/client/gateway/src/server/helpers.rs
  crates/client/gateway/src/server/service.rs
  crates/client/mempool/Cargo.toml
  crates/client/mempool/src/inner.rs
  crates/client/rpc/Cargo.toml
  crates/client/rpc/src/lib.rs
  crates/client/rpc/src/utils/block.rs
  crates/client/rpc/src/utils/mod.rs
  crates/client/rpc/src/versions/v0_7_1/api.rs
  crates/client/rpc/src/versions/v0_7_1/methods/read/lib.rs
  crates/client/rpc/src/versions/v0_8_0/api.rs
  crates/client/rpc/src/versions/v0_8_0/methods/mod.rs
  crates/client/rpc/src/versions/v0_8_0/methods/read/get_compiled_casm.rs
  crates/client/rpc/src/versions/v0_8_0/methods/read/lib.rs
  crates/client/rpc/src/versions/v0_8_0/methods/read/mod.rs
  crates/client/sync/Cargo.toml
  crates/client/telemetry/Cargo.toml
  crates/node/Cargo.toml
  crates/primitives/chain_config/Cargo.toml
  crates/primitives/chain_config/src/rpc_version.rs
  crates/primitives/class/src/lib.rs
  crates/primitives/receipt/Cargo.toml
  crates/primitives/receipt/src/from_blockifier.rs
  crates/tests/Cargo.toml
  crates/tests/src/lib.rs
  crates/tests/src/rpc/read.rs
  crates/tests/src/rpc/test_utils/compiled_class.json
Labels: rpc-0.8.0

#380 build: update blockifier to 0.8.0 and other dependencies
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/client/analytics/Cargo.toml
  crates/client/devnet/src/balances.rs
  crates/client/devnet/src/lib.rs
  crates/client/exec/src/blockifier_state_adapter.rs
  crates/primitives/class/Cargo.toml
  crates/primitives/class/src/compile.rs
  crates/primitives/class/src/convert.rs
  crates/primitives/convert/Cargo.toml
  crates/primitives/convert/src/felt.rs
  crates/primitives/convert/src/lib.rs
  crates/primitives/gateway/src/receipt.rs
  crates/primitives/gateway/src/transaction.rs
  crates/primitives/receipt/Cargo.toml
  crates/primitives/receipt/src/from_starknet_provider.rs
  crates/primitives/receipt/src/lib.rs
  crates/primitives/state_update/Cargo.toml
  crates/primitives/state_update/src/from_provider.rs
  crates/primitives/state_update/src/lib.rs
  crates/primitives/transactions/Cargo.toml
  crates/primitives/transactions/src/from_starknet_provider.rs
  crates/primitives/transactions/src/into_starknet_api.rs
  crates/primitives/transactions/src/lib.rs
  scripts/todo_tree.sh
Labels: enhancement

#381 fix(fgw): include `l1_to_l2_consumed_message` in L1 handler receipt
  CHANGELOG.md
  Cargo.lock
  crates/primitives/convert/Cargo.toml
  crates/primitives/convert/src/felt.rs
  crates/primitives/convert/src/lib.rs
  crates/primitives/gateway/src/block.rs
  crates/primitives/gateway/src/receipt.rs
Labels: bug

#389 fix: FeePayment conversion
  CHANGELOG.md
  crates/client/sync/test-data/block_724130.json
  crates/primitives/gateway/src/receipt.rs
  crates/primitives/gateway/src/transaction.rs
  crates/primitives/receipt/src/lib.rs
Labels: bug

#386 feat(endpoint): added extra `admin` rpc endpoint for sensitive rpc calls
  CHANGELOG.md
  crates/client/gateway/server/src/handler.rs
  crates/client/rpc/src/RPC.md
  crates/client/rpc/src/lib.rs
  crates/client/rpc/src/versions/admin/mod.rs
  crates/client/rpc/src/versions/admin/v0_1_0/api.rs
  crates/client/rpc/src/versions/admin/v0_1_0/methods/mod.rs
  crates/client/rpc/src/versions/admin/v0_1_0/methods/write.rs
  crates/client/rpc/src/versions/admin/v0_1_0/mod.rs
  crates/client/rpc/src/versions/mod.rs
  crates/client/rpc/src/versions/user/mod.rs
  crates/client/rpc/src/versions/user/v0_7_1/api.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/mod.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/block_hash_and_number.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/call.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/estimate_fee.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/estimate_message_fee.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/get_block_transaction_count.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/get_block_with_receipts.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/get_block_with_tx_hashes.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/get_block_with_txs.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/get_class.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/get_class_at.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/get_class_hash_at.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/get_events.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/get_nonce.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/get_state_update.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/get_storage_at.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/get_transaction_by_block_id_and_index.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/get_transaction_by_hash.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/get_transaction_receipt.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/get_transaction_status.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/lib.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/mod.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/syncing.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/trace/mod.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/trace/simulate_transactions.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/trace/trace_block_transactions.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/trace/trace_transaction.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/write/mod.rs
  crates/client/rpc/src/versions/user/v0_7_1/mod.rs
  crates/client/rpc/src/versions/user/v0_8_0/api.rs
  crates/client/rpc/src/versions/user/v0_8_0/methods/mod.rs
  crates/client/rpc/src/versions/user/v0_8_0/methods/read/get_compiled_casm.rs
  crates/client/rpc/src/versions/user/v0_8_0/methods/read/lib.rs
  crates/client/rpc/src/versions/user/v0_8_0/methods/read/mod.rs
  crates/client/rpc/src/versions/user/v0_8_0/methods/ws/lib.rs
  crates/client/rpc/src/versions/user/v0_8_0/methods/ws/mod.rs
  crates/client/rpc/src/versions/user/v0_8_0/mod.rs
  crates/node/src/cli/rpc.rs
  crates/node/src/service/rpc.rs
  crates/node/src/service/rpc/metrics.rs
  crates/node/src/service/rpc/middleware.rs
  crates/node/src/service/rpc/mod.rs
  crates/node/src/service/rpc/server.rs
  crates/primitives/chain_config/src/rpc_version.rs
  crates/proc-macros/src/lib.rs
Labels: enhancement

#390 feat(debug): service cancelling and profiling build
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/client/eth/Cargo.toml
  crates/client/eth/src/l1_gas_price.rs
  crates/client/eth/src/l1_messaging.rs
  crates/client/eth/src/state_update.rs
  crates/client/eth/src/sync.rs
  crates/client/gateway/client/Cargo.toml
  crates/client/gateway/server/Cargo.toml
  crates/client/gateway/server/src/service.rs
  crates/client/mempool/Cargo.toml
  crates/client/mempool/src/block_production.rs
  crates/client/sync/Cargo.toml
  crates/client/sync/src/fetch/fetchers.rs
  crates/client/sync/src/fetch/fetchers_real_fgw_test.rs
  crates/client/sync/src/fetch/mod.rs
  crates/client/sync/src/l2.rs
  crates/client/sync/src/lib.rs
  crates/client/telemetry/Cargo.toml
  crates/client/telemetry/src/lib.rs
  crates/node/Cargo.toml
  crates/node/src/cli/sync.rs
  crates/node/src/service/block_production.rs
  crates/node/src/service/gateway.rs
  crates/node/src/service/l1.rs
  crates/node/src/service/rpc/mod.rs
  crates/node/src/service/rpc/server.rs
  crates/node/src/service/sync.rs
  crates/primitives/utils/Cargo.toml
  crates/primitives/utils/src/lib.rs
  crates/primitives/utils/src/service.rs
Labels: enhancement

#394 fix: fetch class
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/client/gateway/client/src/methods.rs
Labels: bug, full node

#399 docs(readme): updated `README.md` docs and added Docker Compose support
  .gitignore
  CHANGELOG.md
  Dockerfile
  Makefile
  README.md
  compose.yaml
  crates/tests/src/rpc/read.rs
  docker-compose.yml
  madara-runner.sh
Labels: documentation
