Repository madara-alliance/madara, pull requests merged in 2024-12, with the labels that each got.

#292 feat(rpc): storage proofs for snos and v0.8.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/client/analytics/src/lib.rs
  crates/client/block_import/src/pre_validate.rs
  crates/client/db/Cargo.toml
  crates/client/db/src/block_db.rs
  crates/client/db/src/bonsai_db.rs
  crates/client/db/src/db_block_id.rs
  crates/client/db/src/error.rs
  crates/client/db/src/lib.rs
  crates/client/db/src/rocksdb_snapshot.rs
  crates/client/db/src/snapshots.rs
  crates/client/db/src/storage_updates.rs
  crates/client/db/src/tests/test_open.rs
  crates/client/eth/src/l1_messaging.rs
  crates/client/eth/src/state_update.rs
  crates/client/gateway/server/src/handler.rs
  crates/client/rpc/Cargo.toml
  crates/client/rpc/src/errors.rs
  crates/client/rpc/src/lib.rs
  crates/client/rpc/src/test_utils.rs
  crates/client/rpc/src/versions/user/v0_8_0/api.rs
  crates/client/rpc/src/versions/user/v0_8_0/methods/read/get_storage_proof.rs
  crates/client/rpc/src/versions/user/v0_8_0/methods/read/lib.rs
  crates/client/rpc/src/versions/user/v0_8_0/methods/read/mod.rs
  crates/client/rpc/src/versions/v0_8_0/api.rs
  crates/client/rpc/src/versions/v0_8_0/methods/mod.rs
  crates/client/rpc/src/versions/v0_8_0/methods/read/mod.rs
  crates/node/src/cli/db.rs
  crates/node/src/cli/rpc.rs
  crates/node/src/main.rs
  crates/node/src/service/rpc/middleware.rs
  crates/node/src/service/rpc/mod.rs
  crates/primitives/chain_config/src/rpc_version.rs
  crates/tests/src/lib.rs
  crates/tests/src/storage_proof.rs
Labels: enhancement

#368 feat(gas) : fetch strk price from oracle
  .github/workflows/starknet-js-test.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/client/eth/Cargo.toml
  crates/client/eth/src/client.rs
  crates/client/eth/src/l1_gas_price.rs
  crates/client/gateway/client/Cargo.toml
  crates/client/mempool/Cargo.toml
  crates/client/mempool/src/l1.rs
  crates/client/rpc/Cargo.toml
  crates/client/telemetry/Cargo.toml
  crates/node/Cargo.toml
  crates/node/src/cli/l1.rs
  crates/node/src/main.rs
  crates/primitives/oracle/Cargo.toml
  crates/primitives/oracle/src/lib.rs
  crates/primitives/oracle/src/pragma.rs
Labels: sequencer

#405 feat(services): reworked Madara services for better cancellation control
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  crates/client/block_production/src/lib.rs
  crates/client/db/src/bonsai_db.rs
  crates/client/db/src/lib.rs
  crates/client/devnet/src/lib.rs
  crates/client/eth/src/l1_gas_price.rs
  crates/client/eth/src/l1_messaging.rs
  crates/client/eth/src/state_update.rs
  crates/client/eth/src/sync.rs
  crates/client/gateway/client/src/methods.rs
  crates/client/gateway/server/src/handler.rs
  crates/client/gateway/server/src/router.rs
  crates/client/gateway/server/src/service.rs
  crates/client/rpc/src/providers/mod.rs
  crates/client/rpc/src/versions/admin/v0_1_0/api.rs
  crates/client/rpc/src/versions/admin/v0_1_0/methods/services.rs
  crates/client/rpc/src/versions/admin/v0_1_0/methods/write.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/get_block_with_tx_hashes.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/read/get_nonce.rs
  crates/client/rpc/src/versions/user/v0_7_1/methods/write/mod.rs
  crates/client/sync/src/fetch/fetchers.rs
  crates/client/sync/src/fetch/fetchers_real_fgw_test.rs
  crates/client/sync/src/fetch/mod.rs
  crates/client/sync/src/l2.rs
  crates/client/sync/src/lib.rs
  crates/client/sync/src/tests/utils/read_resource.rs
  crates/client/telemetry/src/lib.rs
  crates/node/src/cli/l1.rs
  crates/node/src/cli/l2.rs
  crates/node/src/cli/mod.rs
  crates/node/src/main.rs
  crates/node/src/service/block_production.rs
  crates/node/src/service/gateway.rs
  crates/node/src/service/l1.rs
  crates/node/src/service/l2.rs
  crates/node/src/service/mod.rs
  crates/node/src/service/rpc/mod.rs
  crates/node/src/service/rpc/server.rs
  crates/primitives/transactions/src/lib.rs
  crates/primitives/utils/Cargo.toml
  crates/primitives/utils/src/lib.rs
  crates/primitives/utils/src/service.rs
  crates/proc-macros/Cargo.toml
  crates/proc-macros/src/lib.rs
Labels: enhancement

#432 fix: rpc deploy account
  CHANGELOG.md
  Cargo.lock
  crates/client/devnet/src/lib.rs
  crates/primitives/gateway/src/user_transaction.rs
Labels: bug

#421 update: fixed analytics
  CHANGELOG.md
  crates/node/src/service/rpc/metrics.rs
Labels: bug

#440 fix(gateway): path
  CHANGELOG.md
  crates/client/gateway/server/src/router.rs
Labels: bug

#439 chore(nix): resolve flake and direnv compatibility issues
  .envrc
  CHANGELOG.md
  flake.lock
  flake.nix
Labels: infra
