Repository madara-alliance/madara, pull requests merged in 2024-09, with the labels that each got.

#248 fix: L1 network mismatch
  CHANGELOG.md
  crates/client/eth/src/client.rs
Labels: bug

#235 feat: class import
  CHANGELOG.md
  Cargo.lock
  crates/client/block_import/Cargo.toml
  crates/client/block_import/src/lib.rs
  crates/client/block_import/src/pre_validate.rs
  crates/client/block_import/src/types.rs
  crates/client/db/src/class_db.rs
  crates/client/db/src/storage_updates.rs
  crates/client/exec/src/blockifier_state_adapter.rs
  crates/client/mempool/Cargo.toml
  crates/client/rpc/src/providers/mempool.rs
  crates/client/rpc/src/test_utils.rs
  crates/client/rpc/src/utils/transaction.rs
  crates/client/rpc/src/versions/v0_7_1/methods/read/estimate_fee.rs
  crates/client/rpc/src/versions/v0_7_1/methods/read/get_class.rs
  crates/client/rpc/src/versions/v0_7_1/methods/read/get_class_at.rs
  crates/client/rpc/src/versions/v0_7_1/methods/trace/simulate_transactions.rs
  crates/client/rpc/src/versions/v0_7_1/methods/trace/trace_transaction.rs
  crates/client/sync/Cargo.toml
  crates/client/sync/src/fetch/fetchers.rs
  crates/client/sync/src/l2.rs
  crates/node/Cargo.toml
  crates/node/src/service/l1.rs
  crates/primitives/block/Cargo.toml
  crates/primitives/block/src/header.rs
  crates/primitives/block/src/lib.rs
  crates/primitives/chain_config/Cargo.toml
  crates/primitives/chain_config/src/chain_config.rs
  crates/primitives/chain_config/src/starknet_version.rs
  crates/primitives/class/Cargo.toml
  crates/primitives/class/resources/missed_classes.json
  crates/primitives/class/src/class_hash.rs
  crates/primitives/class/src/class_update.rs
  crates/primitives/class/src/compile.rs
  crates/primitives/class/src/into_starknet_core.rs
  crates/primitives/class/src/lib.rs
  crates/primitives/convert/Cargo.toml
  crates/primitives/state_update/src/lib.rs
  crates/primitives/transactions/src/broadcasted_to_blockifier.rs
  crates/primitives/transactions/src/compute_hash.rs
  crates/primitives/transactions/src/from_broadcasted_transaction.rs
Labels: full node

#256 Fix(deps): Removed unused dependencies with udeps and machete
  CHANGELOG.md
  Cargo.lock
  crates/client/devnet/Cargo.toml
  crates/client/eth/Cargo.toml
  crates/client/exec/Cargo.toml
  crates/client/mempool/Cargo.toml
  crates/primitives/utils/Cargo.toml
  crates/proc-macros/Cargo.toml
  crates/tests/Cargo.toml
Labels: code quality

#245 fix: adding the --starting-from arg back by ignoring ordered state
  CHANGELOG.md
  crates/client/block_import/src/lib.rs
  crates/client/block_import/src/types.rs
  crates/client/block_import/src/verify_apply.rs
  crates/client/sync/src/fetch/fetchers.rs
  crates/client/sync/src/l2.rs
  crates/client/sync/src/lib.rs
  crates/node/src/cli/sync.rs
  crates/node/src/service/sync.rs
Labels: full node

#254 Tests : devnet : declare and deploy account
  .github/workflows/coverage.yml
  CHANGELOG.md
  Cargo.lock
  cairo/.gitignore
  cairo/src/lib.cairo
  cairo/src/test_account.cairo
  cairo/target/dev/madara_contracts_AccountUpgradeable.contract_class.json
  cairo/target/dev/madara_contracts_ERC20.contract_class.json
  cairo/target/dev/madara_contracts_UniversalDeployer.contract_class.json
  crates/client/devnet/Cargo.toml
  crates/client/devnet/build.rs
  crates/client/devnet/src/lib.rs
  crates/client/eth/src/l1_gas_price.rs
Labels: tests

#265 fix: defaulted l1 gas price in devnet mode
  .github/workflows/coverage.yml
  CHANGELOG.md
  crates/node/src/cli/l1.rs
  crates/node/src/main.rs
Labels: bug

#261 fix(devnet): generate a fixed set of public and private keys for devnet
  CHANGELOG.md
  Cargo.lock
  crates/client/devnet/Cargo.toml
  crates/client/devnet/src/lib.rs
  crates/node/src/service/block_production.rs
Labels: sequencer, code quality

#262 fix: flaky test
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  cairo/.tool-versions
  crates/client/eth/Cargo.toml
  crates/client/eth/src/client.rs
  crates/client/eth/src/l1_gas_price.rs
Labels: bug

#255 feat: configurable chain config
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  config.example.yaml
  crates/client/db/Cargo.toml
  crates/client/db/tests/common/mod.rs
  crates/client/db/tests/test_block.rs
  crates/client/db/tests/test_open.rs
  crates/client/devnet/Cargo.toml
  crates/client/devnet/src/lib.rs
  crates/client/eth/src/l1_messaging.rs
  crates/client/eth/src/state_update.rs
  crates/client/rpc/Cargo.toml
  crates/client/rpc/src/test_utils.rs
  crates/node/Cargo.toml
  crates/node/src/cli/chain_config_overrides.rs
  crates/node/src/cli/mod.rs
  crates/node/src/main.rs
  crates/primitives/chain_config/Cargo.toml
  crates/primitives/chain_config/presets/integration.yaml
  crates/primitives/chain_config/presets/mainnet.yaml
  crates/primitives/chain_config/presets/sepolia.yaml
  crates/primitives/chain_config/presets/test.yaml
  crates/primitives/chain_config/src/chain_config.rs
  crates/primitives/utils/Cargo.toml
  crates/primitives/utils/src/lib.rs
  crates/primitives/utils/src/tests_common.rs
  crates/tests/Cargo.toml
  crates/tests/src/lib.rs
  crates/tests/src/rpc/read.rs
Labels: enhancement

#269 refactor: calculate class hash in devnet
  CHANGELOG.md
  crates/client/db/src/devnet_db.rs
  crates/client/devnet/src/classes.rs
  crates/client/devnet/src/lib.rs
  crates/client/devnet/src/predeployed_contracts.rs
  crates/node/src/service/block_production.rs
Labels: bug, enhancement

#253 Integration Test: L2 fetch task
  CHANGELOG.md
  Cargo.lock
  crates/client/sync/Cargo.toml
  crates/client/sync/src/fetch/fetchers.rs
  crates/client/sync/src/fetch/mod.rs
  crates/client/sync/src/lib.rs
  crates/client/sync/src/tests/mod.rs
  crates/client/sync/src/tests/utils/gateway.rs
  crates/client/sync/src/tests/utils/mod.rs
  crates/client/sync/src/tests/utils/read_resource.rs
Labels: tests

#274 fix: spec version
  CHANGELOG.md
  crates/primitives/chain_config/src/rpc_version.rs
Labels: bug

#263 fix : events from call info / UDC cairo 0 migration
  CHANGELOG.md
  Cargo.lock
  cairo_0/madara_contracts_UDC.json
  crates/client/devnet/src/lib.rs
  crates/client/mempool/src/lib.rs
  crates/client/rpc/src/versions/v0_7_1/methods/read/estimate_fee.rs
  crates/primitives/receipt/Cargo.toml
  crates/primitives/receipt/src/from_blockifier.rs
Labels: bug, enhancement

#260 L2 sync: verify and apply task tests
  CHANGELOG.md
  Cargo.lock
  crates/client/block_import/Cargo.toml
  crates/client/block_import/src/lib.rs
  crates/client/block_import/src/tests.rs
  crates/client/block_import/src/tests/block_import_utils.rs
  crates/client/block_import/src/verify_apply.rs
  crates/client/block_import/src/verify_apply/classes.rs
  crates/client/block_import/src/verify_apply/contracts.rs
  crates/client/db/Cargo.toml
  crates/client/db/src/lib.rs
  crates/client/db/src/tests.rs
  crates/client/db/src/tests/common/mod.rs
  crates/client/db/src/tests/test_block.rs
  crates/client/db/src/tests/test_open.rs
  crates/client/db/tests/common/mod.rs
  crates/client/db/tests/test_block.rs
  crates/client/sync/src/tests/utils/gateway.rs
Labels: tests

#271 fix(block-production): fix bouncer, error reporting, debug messages
  .github/workflows/coverage.yml
  .github/workflows/linters-cargo.yml
  .github/workflows/rust-check.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  cairo/Scarb.toml
  crates/client/block_import/Cargo.toml
  crates/client/block_import/src/lib.rs
  crates/client/block_import/src/metrics.rs
  crates/client/block_import/src/pre_validate.rs
  crates/client/block_import/src/types.rs
  crates/client/block_import/src/verify_apply.rs
  crates/client/db/src/db_metrics.rs
  crates/client/db/src/lib.rs
  crates/client/db/src/tests/common/mod.rs
  crates/client/db/src/tests/test_open.rs
  crates/client/devnet/Cargo.toml
  crates/client/devnet/src/lib.rs
  crates/client/eth/src/client.rs
  crates/client/eth/src/l1_messaging.rs
  crates/client/eth/src/state_update.rs
  crates/client/exec/src/blockifier_state_adapter.rs
  crates/client/exec/src/lib.rs
  crates/client/mempool/src/block_production.rs
  crates/client/mempool/src/close_block.rs
  crates/client/mempool/src/inner.rs
  crates/client/mempool/src/lib.rs
  crates/client/metrics/src/lib.rs
  crates/client/rpc/src/errors.rs
  crates/client/rpc/src/providers/mempool.rs
  crates/client/sync/src/fetch/fetchers.rs
  crates/client/sync/src/l2.rs
  crates/client/sync/src/lib.rs
  crates/node/src/main.rs
  crates/node/src/service/block_production.rs
  crates/node/src/service/l1.rs
  crates/node/src/service/rpc.rs
  crates/node/src/service/sync.rs
  crates/node/src/util.rs
  crates/primitives/chain_config/presets/integration.yaml
  crates/primitives/chain_config/presets/mainnet.yaml
  crates/primitives/chain_config/presets/sepolia.yaml
  crates/primitives/chain_config/presets/test.yaml
  crates/primitives/chain_config/src/chain_config.rs
  crates/primitives/class/Cargo.toml
  crates/primitives/class/src/class_hash.rs
  crates/primitives/class/src/convert.rs
  crates/primitives/class/src/lib.rs
  crates/primitives/convert/src/lib.rs
  crates/primitives/convert/src/to_felt.rs
  crates/primitives/transactions/Cargo.toml
  crates/primitives/transactions/src/broadcasted_to_blockifier.rs
Labels: bug

#273 feat(infra): move to karnot self hosted runner
  .env.test
  .github/workflows/changelog.yml
  .github/workflows/coverage.yml
  .github/workflows/linters-cargo.yml
  .github/workflows/linters.yml
  .github/workflows/pull-request-close.yml
  .github/workflows/pull-request.yml
  .github/workflows/rust-check.yml
  .github/workflows/rust-test.yml
  .github/workflows/security-audit.yml
  .github/workflows/stale-issues.yml
  CHANGELOG.md
  Cargo.lock
  crates/client/eth/Cargo.toml
  crates/client/eth/src/client.rs
  crates/client/eth/src/l1_gas_price.rs
Labels: infra

#279 fix(cli): Fix and clean client modes and fetch presets
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  configs/chain_config.example.yaml
  configs/presets/devnet.yaml
  configs/presets/integration.yaml
  configs/presets/mainnet.yaml
  configs/presets/sepolia.yaml
  crates/client/block_import/src/verify_apply.rs
  crates/client/db/src/tests/common/mod.rs
  crates/client/db/src/tests/test_block.rs
  crates/client/db/src/tests/test_open.rs
  crates/client/devnet/src/lib.rs
  crates/client/eth/src/l1_messaging.rs
  crates/client/eth/src/state_update.rs
  crates/client/rpc/src/test_utils.rs
  crates/client/sync/src/fetch/fetchers.rs
  crates/client/sync/src/fetch/mod.rs
  crates/client/sync/src/tests/utils/gateway.rs
  crates/node/Cargo.toml
  crates/node/src/cli/block_production.rs
  crates/node/src/cli/chain_config_overrides.rs
  crates/node/src/cli/l1.rs
  crates/node/src/cli/mod.rs
  crates/node/src/cli/sync.rs
  crates/node/src/main.rs
  crates/node/src/service/block_production.rs
  crates/node/src/service/l1.rs
  crates/node/src/service/sync.rs
  crates/primitives/chain_config/Cargo.toml
  crates/primitives/chain_config/src/chain_config.rs
  crates/primitives/utils/Cargo.toml
  crates/primitives/utils/src/lib.rs
  crates/primitives/utils/src/parsers.rs
  crates/primitives/utils/src/serde.rs
  crates/primitives/utils/src/tests_common.rs
  crates/tests/src/lib.rs
  crates/tests/src/rpc/read.rs
Labels: bug, enhancement
