Repository madara-alliance/madara, pull requests merged in 2024-10, with the labels that each got.

#282 feat(cli): updating madara launcher to support full, sequencer, devnet modes
  .github/workflows/docker-build.yml
  .github/workflows/release.yml
  CHANGELOG.md
  Dockerfile
  scripts/launcher
Labels: documentation, enhancement, infra

#283 feat(test): block conversion on sync tests
  CHANGELOG.md
  Cargo.lock
  crates/client/block_import/Cargo.toml
  crates/client/block_import/src/tests.rs
  crates/client/block_import/src/tests/block_import_utils.rs
  crates/client/sync/Cargo.toml
  crates/client/sync/src/l2.rs
Labels: tests

#284 feat(test): adding JS tests to the CI
  .github/workflows/build.yml
  .github/workflows/pull-request.yml
  .github/workflows/starknet-js-test.yml
  .gitignore
  CHANGELOG.md
  cairo/Scarb.toml
  cairo/src/hello.cairo
  cairo/src/lib.cairo
  crates/client/eth/src/client.rs
  crates/tests/src/lib.rs
  crates/tests/src/rpc/read.rs
  tests/js_tests/.gitignore
  tests/js_tests/basic.test.ts
  tests/js_tests/constant.ts
  tests/js_tests/jest.config.cjs
  tests/js_tests/package.json
  tests/js_tests/tsconfig.json
  tests/js_tests/utils.ts
Labels: tests

#304 fix(sync): pending block retrying mechanism & flaky tests
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/client/gateway/Cargo.toml
  crates/client/gateway/src/client/methods.rs
  crates/client/gateway/src/client/request_builder.rs
  crates/client/gateway/src/error.rs
  crates/client/sync/src/fetch/fetchers.rs
  crates/client/sync/src/fetch/fetchers_real_fgw_test.rs
  crates/client/sync/src/l2.rs
  crates/tests/src/lib.rs
  crates/tests/src/rpc/read.rs
  scripts/e2e-tests.sh
Labels: bug

#311 feat(cli): Madara configuration via environment variables
  CHANGELOG.md
  README.md
  crates/node/Cargo.toml
  crates/node/src/cli/block_production.rs
  crates/node/src/cli/chain_config_overrides.rs
  crates/node/src/cli/db.rs
  crates/node/src/cli/gateway.rs
  crates/node/src/cli/l1.rs
  crates/node/src/cli/mod.rs
  crates/node/src/cli/prometheus.rs
  crates/node/src/cli/rpc.rs
  crates/node/src/cli/sync.rs
  crates/node/src/cli/telemetry.rs
Labels: enhancement

#312 fix: override cli
  CHANGELOG.md
  Cargo.lock
  configs/chain_config.example.yaml
  configs/presets/devnet.yaml
  configs/presets/integration.yaml
  configs/presets/mainnet.yaml
  configs/presets/sepolia.yaml
  crates/client/block_import/Cargo.toml
  crates/client/db/Cargo.toml
  crates/client/devnet/Cargo.toml
  crates/client/rpc/Cargo.toml
  crates/client/sync/Cargo.toml
  crates/node/Cargo.toml
  crates/node/src/cli/chain_config_overrides.rs
  crates/primitives/chain_config/Cargo.toml
  crates/primitives/chain_config/src/chain_config.rs
  crates/primitives/class/Cargo.toml
  crates/primitives/receipt/Cargo.toml
  crates/primitives/utils/Cargo.toml
  crates/primitives/utils/src/parsers.rs
  crates/primitives/utils/src/serde.rs
  crates/tests/Cargo.toml
Labels: sequencer

#305 fix(script): Fix final touches over launcher script
  .github/workflows/starknet-js-test.yml
  CHANGELOG.md
  README.md
  crates/client/telemetry/src/lib.rs
  crates/node/src/cli/telemetry.rs
  crates/node/src/main.rs
  crates/primitives/chain_config/src/chain_config.rs
  crates/tests/src/lib.rs
  scripts/launcher
Labels: documentation, enhancement

#307 fix(fgw): sync from other nodes and block signature
  .github/workflows/starknet-js-test.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  configs/presets/devnet.yaml
  configs/presets/integration.yaml
  configs/presets/mainnet.yaml
  configs/presets/sepolia.yaml
  crates/client/block_import/src/types.rs
  crates/client/block_import/src/verify_apply.rs
  crates/client/gateway/Cargo.toml
  crates/client/gateway/src/client/methods.rs
  crates/client/gateway/src/client/mocks/signature_block_0.gz
  crates/client/gateway/src/client/mocks/signature_block_1.gz
  crates/client/gateway/src/client/mocks/signature_block_2.gz
  crates/client/gateway/src/error.rs
  crates/client/gateway/src/server/handler.rs
  crates/client/gateway/src/server/helpers.rs
  crates/client/gateway/src/server/router.rs
  crates/client/sync/src/fetch/mod.rs
  crates/client/sync/src/tests/utils/gateway.rs
  crates/client/sync/test-data/block_0.json
  crates/client/sync/test-data/block_724130.json
  crates/node/Cargo.toml
  crates/node/src/cli/chain_config_overrides.rs
  crates/node/src/main.rs
  crates/node/src/service/gateway.rs
  crates/primitives/chain_config/Cargo.toml
  crates/primitives/chain_config/src/chain_config.rs
  crates/primitives/class/src/compile.rs
  crates/primitives/class/src/lib.rs
  crates/primitives/gateway/src/block.rs
  crates/primitives/gateway/src/receipt.rs
  crates/primitives/utils/Cargo.toml
  crates/primitives/utils/src/crypto.rs
  crates/primitives/utils/src/lib.rs
  crates/primitives/utils/src/parsers.rs
  crates/primitives/utils/src/serde.rs
Labels: bug

#318 fix(sync): pipeline stalling on machines with few cpu cores
  CHANGELOG.md
  Cargo.toml
  crates/client/block_import/src/lib.rs
  crates/client/block_import/src/pre_validate.rs
  crates/client/block_import/src/rayon.rs
  crates/client/block_import/src/verify_apply.rs
Labels: bug

#354 fix(block_hash): Block hash mismatch for transaction with an empty signature
  CHANGELOG.md
  crates/primitives/block/src/header.rs
  crates/primitives/transactions/src/compute_hash.rs
Labels: bug

#350 refactor(rpc): re-worked rpc tower server and added proper websocket support
  CHANGELOG.md
  Cargo.lock
  crates/client/rpc/src/RPC.md
  crates/client/rpc/src/lib.rs
  crates/client/rpc/src/macros.rs
  crates/client/rpc/src/versions/v0_7_1/api.rs
  crates/node/src/cli/rpc.rs
  crates/node/src/service/rpc.rs
  crates/node/src/service/rpc/middleware.rs
  crates/node/src/service/rpc/server.rs
  crates/primitives/chain_config/Cargo.toml
  crates/primitives/chain_config/src/rpc_version.rs
  crates/proc-macros/src/lib.rs
Labels: rpc-0.8.0

#353 Feat/deprecated classes
  CHANGELOG.md
  crates/client/mempool/src/block_production.rs
  crates/client/sync/src/utils.rs
Labels: bug, sequencer

#358 fix(namespace): versioning now works for methods without `starknet` namespace
  CHANGELOG.md
  crates/node/src/service/rpc/middleware.rs
Labels: bug

#364 ref(fgw): replacing the reqwest feeder client with hyper
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/client/gateway/Cargo.toml
  crates/client/gateway/src/client/builder.rs
  crates/client/gateway/src/client/methods.rs
  crates/client/gateway/src/client/request_builder.rs
  crates/client/gateway/src/error.rs
  crates/client/gateway/src/server/error.rs
  crates/client/gateway/src/server/handler.rs
  crates/client/gateway/src/server/helpers.rs
  crates/client/gateway/src/server/router.rs
  crates/client/gateway/src/server/service.rs
  crates/client/metrics/Cargo.toml
  crates/client/metrics/src/lib.rs
  crates/client/rpc/Cargo.toml
  crates/client/sync/Cargo.toml
  crates/client/sync/src/fetch/fetchers.rs
  crates/client/sync/src/lib.rs
  crates/node/Cargo.toml
  crates/primitives/class/src/lib.rs
  crates/primitives/utils/Cargo.toml
Labels: full node

#359 feat(v0.8.0-rc0): starknet_subscribeNewHeads
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/client/db/src/block_db.rs
  crates/client/db/src/lib.rs
  crates/client/rpc/Cargo.toml
  crates/client/rpc/src/errors.rs
  crates/client/rpc/src/lib.rs
  crates/client/rpc/src/versions/mod.rs
  crates/client/rpc/src/versions/v0_7_1/api.rs
  crates/client/rpc/src/versions/v0_8_0/api.rs
  crates/client/rpc/src/versions/v0_8_0/methods/mod.rs
  crates/client/rpc/src/versions/v0_8_0/methods/ws/lib.rs
  crates/client/rpc/src/versions/v0_8_0/methods/ws/mod.rs
  crates/client/rpc/src/versions/v0_8_0/mod.rs
  crates/node/src/service/rpc/server.rs
  crates/primitives/block/Cargo.toml
  crates/primitives/block/src/lib.rs
  crates/proc-macros/src/lib.rs
Labels: rpc-0.8.0
