Repository madara-alliance/madara, pull requests merged in 2025-05, with the labels that each got.

#626 update: updated default values in the presets
  configs/chain_config.example.yaml
  configs/presets/devnet.yaml
  configs/presets/integration.yaml
  configs/presets/mainnet.yaml
  configs/presets/sepolia.yaml
  madara/crates/primitives/chain_config/src/chain_config.rs
Labels: bug

#634 ci(New_RPC_URL) Updated the New RPC URL for tests
  .env.test
Labels: CI / CD, enhancement

#635 feat(Makefile): Makefile Commands for New Developers - [ Improved development workflow ]
  .githooks/pre-push
  Makefile
Labels: docs, code-quality, CI / CD

#648 style: format code and improve readability in tests and initialization scripts
  Makefile
Labels: code-quality, CI / CD

#644 fix: madara to handle block 0 state
  .prettierignore
  madara/crates/client/settlement_client/src/eth/mod.rs
  madara/crates/client/settlement_client/src/starknet/mod.rs
  madara/crates/client/settlement_client/src/starknet/utils.rs
  madara/crates/client/settlement_client/src/state_update.rs
  madara/crates/client/settlement_client/src/utils.rs
  madara/crates/client/sync/src/sync.rs
  madara/crates/client/sync/src/tests/pipeline.rs
Labels: bug

#657 Chain Config : L1DataAvailabilityMode added
  Cargo.lock
  configs/chain_config.example.yaml
  configs/chain_config.template.yml
  configs/presets/devnet.yaml
  configs/presets/integration.yaml
  configs/presets/mainnet.yaml
  configs/presets/sepolia.yaml
  madara/crates/client/block_production/src/lib.rs
  madara/crates/client/db/src/block_db.rs
  madara/crates/client/devnet/src/lib.rs
  madara/crates/client/exec/src/block_context.rs
  madara/crates/client/mempool/src/header.rs
  madara/crates/client/mempool/src/l1.rs
  madara/crates/client/rpc/src/test_utils.rs
  madara/crates/client/rpc/src/versions/user/v0_7_1/methods/read/get_block_with_receipts.rs
  madara/crates/node/src/cli/chain_config_overrides.rs
  madara/crates/primitives/block/src/commitments.rs
  madara/crates/primitives/block/src/header.rs
  madara/crates/primitives/block/src/lib.rs
  madara/crates/primitives/chain_config/Cargo.toml
  madara/crates/primitives/chain_config/src/chain_config.rs
  madara/crates/primitives/chain_config/src/l1_da_mode.rs
  madara/crates/primitives/chain_config/src/lib.rs
  madara/crates/primitives/gateway/src/block.rs
Labels: feature

#653 feat(database): enhance MongoDB client with Pre Setup PR for L3
  Makefile
  e2e-tests/src/node.rs
  orchestrator/crates/orchestrator/src/cli/mod.rs
  orchestrator/crates/orchestrator/src/core/client/database/mongodb.rs
  orchestrator/crates/orchestrator/src/core/traits/resource.rs
  orchestrator/crates/orchestrator/src/setup/aws/event_bus.rs
  orchestrator/crates/orchestrator/src/setup/aws/pub_sub.rs
  orchestrator/crates/orchestrator/src/setup/aws/s3.rs
  orchestrator/crates/orchestrator/src/setup/aws/sqs.rs
  orchestrator/crates/orchestrator/src/setup/factory.rs
  orchestrator/crates/orchestrator/src/setup/mod.rs
  orchestrator/crates/orchestrator/src/setup/queue.rs
  orchestrator/crates/orchestrator/src/tests/config.rs
Labels: orchestrator, enhancement

#664 refactor: update Resource trait methods to accept Layer references instead of values
  orchestrator/crates/orchestrator/src/core/traits/resource.rs
  orchestrator/crates/orchestrator/src/setup/aws/event_bus.rs
  orchestrator/crates/orchestrator/src/setup/aws/pub_sub.rs
  orchestrator/crates/orchestrator/src/setup/aws/s3.rs
  orchestrator/crates/orchestrator/src/setup/aws/sqs.rs
  orchestrator/crates/orchestrator/src/setup/factory.rs
  orchestrator/crates/orchestrator/src/tests/config.rs
Labels: bug

#473 feat: store event bloom filter in DB
  .db-versions.yml
  Cargo.lock
  Cargo.toml
  madara/crates/client/db/Cargo.toml
  madara/crates/client/db/src/block_db.rs
  madara/crates/client/db/src/events.rs
  madara/crates/client/db/src/events_bloom_filter.rs
  madara/crates/client/db/src/lib.rs
  madara/crates/client/db/src/storage_updates.rs
  madara/crates/client/rpc/Cargo.toml
  madara/crates/client/rpc/src/utils/mod.rs
  madara/crates/client/rpc/src/versions/user/v0_7_1/methods/read/get_events.rs
  madara/crates/client/rpc/src/versions/user/v0_8_0/methods/ws/subscribe_events.rs
  madara/crates/client/sync/Cargo.toml
  madara/crates/client/sync/src/import.rs
  madara/crates/primitives/block/src/event_with_info.rs
  madara/crates/primitives/block/src/lib.rs
  madara/crates/primitives/bloom_filter/Cargo.toml
  madara/crates/primitives/bloom_filter/benches/bloom_benchmark.rs
  madara/crates/primitives/bloom_filter/src/filter.rs
  madara/crates/primitives/bloom_filter/src/lib.rs
  madara/crates/primitives/bloom_filter/src/storage.rs
  madara/crates/primitives/bloom_filter/src/tests/filter_tests.rs
  madara/crates/primitives/bloom_filter/src/tests/mod.rs
  madara/crates/primitives/bloom_filter/src/tests/proptest.rs
  madara/crates/primitives/bloom_filter/src/tests/serialization.rs
  madara/crates/primitives/bloom_filter/src/tests/utils.rs
Labels: feature, node, performance, db-migration
