Repository madara-alliance/madara, pull requests merged in 2025-01, with the labels that each got.

#446 fix(ci): migrated changelog action on releases for conventional commits only
  .github/workflows/changelog.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: infra

#431 feat(db): add database version management system
  .db-versions.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/labels.yml
  .github/workflows/db-version.yml
  .github/workflows/pull-request.yml
  README.md
  crates/madara/client/db/build.rs
  crates/madara/client/db/src/db_version.rs
  crates/madara/client/db/src/lib.rs
  flake.nix
  scripts/update-db-version.sh
Labels: enhancement

#445 fix(compilation): crate-level compilation
  CHANGELOG.md
  Cargo.lock
  crates/madara/client/db/src/lib.rs
  crates/madara/client/db/src/tests/common/mod.rs
  crates/madara/client/eth/Cargo.toml
  crates/madara/primitives/oracle/Cargo.toml
  crates/madara/primitives/oracle/src/pragma.rs
  crates/madara/primitives/utils/src/serde.rs
Labels: bug

#453 chore(nix): add scarb package manager to development tools
  flake.nix
  tools/scarb.nix
Labels: infra

#438 fix(rpc): call, simulate, estimate rpcs executed on top of the block, not at the start of it
  CHANGELOG.md
  crates/madara/client/block_production/src/lib.rs
  crates/madara/client/exec/src/block_context.rs
  crates/madara/client/exec/src/call.rs
  crates/madara/client/exec/src/execution.rs
  crates/madara/client/exec/src/lib.rs
  crates/madara/client/mempool/src/lib.rs
  crates/madara/client/rpc/src/versions/user/v0_7_1/methods/read/call.rs
  crates/madara/client/rpc/src/versions/user/v0_7_1/methods/read/estimate_fee.rs
  crates/madara/client/rpc/src/versions/user/v0_7_1/methods/read/estimate_message_fee.rs
  crates/madara/client/rpc/src/versions/user/v0_7_1/methods/trace/simulate_transactions.rs
  crates/madara/client/rpc/src/versions/user/v0_7_1/methods/trace/trace_block_transactions.rs
  crates/madara/client/rpc/src/versions/user/v0_7_1/methods/trace/trace_transaction.rs
Labels: bug, full node

#452 chore(ci): add labels sync workflow
  .github/PULL_REQUEST_TEMPLATE.md
  .github/config/labels.yml
  .github/labels.yml
  .github/workflows/db-version.yml
  .github/workflows/sync-labels.yml
  scripts/update-db-version.sh
Labels: infra

#456 fix(block_production): dynamic block closing
  CHANGELOG.md
  crates/madara/client/block_production/src/lib.rs
Labels: bug, sequencer

#448 fix(devnet): loosened devnet chain id restrictions
  README.md
  crates/madara/node/src/cli/block_production.rs
  crates/madara/node/src/cli/mod.rs
  crates/madara/node/src/main.rs
Labels: bug, sequencer

#457 ci: prevent color code from being parsed as number in labels config
  .github/config/labels.yml
Labels: infrastructure

#460 chore(ci): minor fixes to improve CI workflow
  .github/workflows/coverage.yml
  .github/workflows/db-version.yml
  .github/workflows/pull-request.yml
  Cargo.lock
  Cargo.toml
  crates/madara/client/eth/Cargo.toml
  crates/madara/client/eth/src/client.rs
  crates/madara/client/eth/src/l1_gas_price.rs
  scripts/e2e-coverage.sh
  scripts/e2e-tests.sh
  scripts/update-db-version.sh
Labels: infrastructure

#436 refactor(gateway): user transaction improvements - hex serialization & query-only removal
  crates/madara/client/gateway/server/src/handler.rs
  crates/madara/client/rpc/src/errors.rs
  crates/madara/client/rpc/src/providers/forward_to_provider.rs
  crates/madara/primitives/class/src/into_starknet_types.rs
  crates/madara/primitives/class/src/lib.rs
  crates/madara/primitives/gateway/src/user_transaction.rs
  crates/madara/primitives/transactions/src/to_blockifier.rs
Labels: bug

#450 fix(mempool): nonce ordering
  .db-versions.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  crates/madara/client/block_production/src/lib.rs
  crates/madara/client/block_production/src/re_add_finalized_to_blockifier.rs
  crates/madara/client/db/build.rs
  crates/madara/client/db/src/l1_db.rs
  crates/madara/client/db/src/mempool_db.rs
  crates/madara/client/devnet/src/lib.rs
  crates/madara/client/eth/src/l1_messaging.rs
  crates/madara/client/mempool/Cargo.toml
  crates/madara/client/mempool/proptest-regressions/inner.txt
  crates/madara/client/mempool/proptest-regressions/inner/proptest.txt
  crates/madara/client/mempool/src/inner/deployed_contracts.rs
  crates/madara/client/mempool/src/inner/intent.rs
  crates/madara/client/mempool/src/inner/limits.rs
  crates/madara/client/mempool/src/inner/mod.rs
  crates/madara/client/mempool/src/inner/nonce_chain.rs
  crates/madara/client/mempool/src/inner/nonce_mapping.rs
  crates/madara/client/mempool/src/inner/proptest.rs
  crates/madara/client/mempool/src/inner/tx.rs
  crates/madara/client/mempool/src/lib.rs
  crates/madara/client/rpc/src/providers/mempool.rs
  scripts/js-tests.sh
Labels: bug, sequencer, db-migration

#462 chore(docker): fix build and signal
  Dockerfile
  madara-runner.sh
Labels: infrastructure

#459 fix(primitives): limit legacy class sizes
  CHANGELOG.md
  crates/madara/primitives/class/src/convert.rs
Labels: bug, node

#470 fix(l1_receipt): trimmed hash
  crates/madara/primitives/receipt/src/to_starknet_types.rs
Labels: bug

#466 feat(rpc): implement starknet_subscribeEvents WebSocket endpoint
  .github/workflows/db-version.yml
  .github/workflows/linters.yml
  .github/workflows/pull-request.yml
  Cargo.lock
  README.md
  crates/madara/client/db/Cargo.toml
  crates/madara/client/db/src/block_db.rs
  crates/madara/client/db/src/lib.rs
  crates/madara/client/gateway/client/Cargo.toml
  crates/madara/client/gateway/server/Cargo.toml
  crates/madara/client/mempool/Cargo.toml
  crates/madara/client/rpc/src/utils/mod.rs
  crates/madara/client/rpc/src/versions/user/v0_7_1/methods/read/get_events.rs
  crates/madara/client/rpc/src/versions/user/v0_8_0/api.rs
  crates/madara/client/rpc/src/versions/user/v0_8_0/methods/ws/lib.rs
  crates/madara/client/rpc/src/versions/user/v0_8_0/methods/ws/mod.rs
  crates/madara/client/rpc/src/versions/user/v0_8_0/methods/ws/subscribe_events.rs
  crates/madara/client/rpc/src/versions/user/v0_8_0/methods/ws/subscribe_new_heads.rs
  crates/madara/node/Cargo.toml
  crates/madara/primitives/receipt/src/lib.rs
  crates/madara/primitives/utils/Cargo.toml
  crates/madara/tests/Cargo.toml
  rust-toolchain.toml
  taplo/taplo.toml
Labels: rpc-v0.8.0

#465 refactor(rpc): removed redundant v0.8.0 folder
  crates/madara/client/rpc/src/versions/v0_8_0/api.rs
  crates/madara/client/rpc/src/versions/v0_8_0/methods/mod.rs
  crates/madara/client/rpc/src/versions/v0_8_0/methods/read/mod.rs
Labels: code-quality

#468 feat(pending): pending block sealed instead of re-added to mempool
  crates/madara/client/block_production/src/lib.rs
  crates/madara/client/block_production/src/re_add_finalized_to_blockifier.rs
  crates/madara/client/db/src/block_db.rs
  crates/madara/client/db/src/storage_updates.rs
  crates/madara/client/devnet/src/lib.rs
  crates/madara/client/mempool/src/inner/mod.rs
  crates/madara/client/mempool/src/lib.rs
  crates/madara/node/src/service/block_production.rs
  crates/madara/primitives/block/src/lib.rs
  crates/madara/tests/src/devnet.rs
Labels: feature, sequencer

#474 fix(cargo): organized main Cargo.toml
  Cargo.toml
Labels: code-quality
