Repository madara-alliance/madara, pull requests merged in 2025-04, with the labels that each got.

#496 bugfix(rpc): Fix proof RPC
  Cargo.lock
  madara/crates/client/rpc/Cargo.toml
  madara/crates/client/rpc/src/versions/user/v0_8_0/api.rs
  madara/crates/client/rpc/src/versions/user/v0_8_0/methods/read/get_storage_proof.rs
  madara/crates/tests/src/storage_proof.rs
Labels: bug, rpc-v0.8.0

#542 fix(cli): private key input
  Cargo.lock
  Cargo.toml
  madara/crates/node/src/cli/chain_config_overrides.rs
  madara/crates/node/src/cli/mod.rs
  madara/crates/primitives/chain_config/src/chain_config.rs
  madara/crates/primitives/utils/Cargo.toml
  madara/crates/primitives/utils/src/crypto.rs
  madara/crates/primitives/utils/src/serde.rs
Labels: bug

#530 fix: declare_v0
  madara/crates/client/mempool/src/lib.rs
  madara/crates/client/rpc/src/providers/forward_to_provider.rs
  madara/crates/client/rpc/src/providers/mempool.rs
  madara/crates/client/rpc/src/providers/mod.rs
  madara/crates/client/rpc/src/test_utils.rs
  madara/crates/client/rpc/src/versions/admin/v0_1_0/api.rs
  madara/crates/client/rpc/src/versions/admin/v0_1_0/methods/write.rs
  madara/crates/primitives/rpc/src/admin/mod.rs
  madara/crates/primitives/rpc/src/lib.rs
  madara/crates/primitives/transactions/src/from_broadcasted_transaction.rs
  madara/crates/primitives/transactions/src/lib.rs
  madara/crates/primitives/transactions/src/to_blockifier.rs
Labels: bug

#558 ci: Add dockerhub credentials
  .github/workflows/task-coverage-orchestrator.yml
  .github/workflows/task-test-orchestrator-e2e.yml
Labels: infrastructure

#562 fix: Orchestrator test workflow
  .env.test
  .github/workflows/task-coverage-orchestrator.yml
  orchestrator/crates/settlement-clients/starknet/src/lib.rs
  orchestrator/crates/settlement-clients/starknet/src/tests/setup.rs
  orchestrator/crates/settlement-clients/starknet/src/tests/test.rs
Labels: infrastructure, Project Orch

#552 Update deps & Address conversion function
  Cargo.lock
  Cargo.toml
  e2e-tests/Cargo.toml
  orchestrator/crates/orchestrator/Cargo.toml
  orchestrator/crates/orchestrator/src/cli/mod.rs
  orchestrator/crates/prover-clients/atlantic-service/Cargo.toml
  orchestrator/crates/prover-clients/atlantic-service/src/lib.rs
  orchestrator/crates/prover-clients/gps-fact-checker/Cargo.toml
  orchestrator/crates/prover-clients/gps-fact-checker/src/lib.rs
  orchestrator/crates/prover-clients/sharp-service/Cargo.toml
  orchestrator/crates/prover-clients/sharp-service/src/lib.rs
  orchestrator/crates/settlement-clients/ethereum/Cargo.toml
  orchestrator/crates/settlement-clients/ethereum/src/clients/interfaces/validity_interface.rs
  orchestrator/crates/settlement-clients/ethereum/src/conversion.rs
  orchestrator/crates/settlement-clients/ethereum/src/lib.rs
  orchestrator/crates/settlement-clients/ethereum/src/tests/mod.rs
  orchestrator/crates/settlement-clients/ethereum/src/types.rs
  orchestrator/crates/utils/Cargo.toml
  orchestrator/crates/utils/src/lib.rs
Labels: bug, feature

#569 fix: trace api match spec
  madara/crates/client/rpc/src/versions/user/v0_7_1/api.rs
  madara/crates/client/rpc/src/versions/user/v0_7_1/methods/trace/mod.rs
  madara/crates/client/rpc/src/versions/user/v0_7_1/methods/trace/trace_transaction.rs
  madara/crates/primitives/rpc/src/v0_7_1/starknet_trace_api_openrpc.rs
Labels: bug

#559 Processing lock on Proving job
  .gitignore
  Cargo.lock
  orchestrator/crates/orchestrator/src/cli/mod.rs
  orchestrator/crates/orchestrator/src/cli/service.rs
  orchestrator/crates/orchestrator/src/config.rs
  orchestrator/crates/orchestrator/src/helpers.rs
  orchestrator/crates/orchestrator/src/jobs/da_job/mod.rs
  orchestrator/crates/orchestrator/src/jobs/snos_job/mod.rs
  orchestrator/crates/orchestrator/src/tests/config.rs
Labels: performance, Project Orch

#526 fix: syncing endpoint fixed as per spec
  madara/crates/client/db/src/block_db.rs
  madara/crates/client/db/src/lib.rs
  madara/crates/client/gateway/client/src/methods.rs
  madara/crates/client/rpc/src/lib.rs
  madara/crates/client/rpc/src/versions/user/v0_7_1/methods/read/syncing.rs
  madara/crates/client/sync/src/gateway/mod.rs
  madara/crates/client/sync/src/l2.rs
  madara/crates/client/sync/src/sync.rs
  madara/crates/node/src/service/l2.rs
Labels: bug, node

#585 fix: nix development environment
  Makefile
  flake.lock
  flake.nix
Labels: infrastructure
